# Generated by Django 2.2 on 2019-05-09 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_synced_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
