# Generated by Django 2.2 on 2019-05-02 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20190502_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='last_synced_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 21, 23, 30, 307354, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
