# Generated by Django 2.2 on 2019-05-03 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20190503_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='content_snippet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_synced_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 3, 5, 25, 10, 902826, tzinfo=utc)),
        ),
    ]
