# Generated by Django 2.2 on 2019-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20190509_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url',
            field=models.URLField(max_length=500),
        ),
    ]
