# Generated by Django 2.2 on 2019-05-03 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20190503_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='content_snippet',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_synced_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 3, 5, 27, 10, 876723, tzinfo=utc)),
        ),
    ]
