# Generated by Django 2.2 on 2019-05-02 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20190502_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='podcast.Category'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_synced_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 2, 23, 6, 21, 926266, tzinfo=utc)),
        ),
    ]
