# Generated by Django 2.2 on 2019-05-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('identifier', 'page')},
            },
        ),
    ]
