# Generated by Django 2.2 on 2019-05-02 21:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAPIRequestLog',
            fields=[
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_framework_tracking.apirequestlog',),
        ),
    ]
