# Generated by Django 2.2 on 2019-05-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_tracking', '0007_merge_20180419_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSAPIRequestLog',
            fields=[
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_framework_tracking.apirequestlog',),
        ),
    ]
